src/accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.LoginView.as_view(), name="login"),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('password-change/', views.PasswordChangeView.as_view(),
         name='password-change'),
    path('password-reset/', views.PasswordResetView.as_view(),
         name='password-reset'),
    path('password-reset-done/', views.PasswordResetDoneView.as_view(),
         name='password-reset-done'),
    path('password-reset/<uuid:uidb64>/<slug:token>/',
         views.PasswordResetConfirmView.as_view(),
         name='password-reset-confirm'),
]

src/profiles/urls.py
from django.urls import path
from . import views

app_name = 'profiles'
urlpatterns = [
    path('me/', views.ShowProfile.as_view(), name='show_self'),
    path('me/edit/', views.EditProfile.as_view(), name='edit_self'),
    path('<slug:slug>/', views.ShowProfile.as_view(), name='show'),
]

src/profiles/models.py
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible
import uuid
import datetime
from django.db import models
from django.conf import settings
from accounts.models import TimeStampedModel

class Address(TimeStampedModel):
    user = models.ForeignKey('authtools.user', models.DO_NOTHING, blank=True, null=True)
    street = models.CharField(max_length=255, blank=True, null=True)
    city = models.CharField(max_length=64, blank=True, null=True)
    postal_code = models.CharField(max_length=32, blank=True, null=True)
    province = models.ForeignKey('Province', models.DO_NOTHING, blank=True, null=True)
    region = models.ForeignKey('Region', models.DO_NOTHING, blank=True, null=True)
    country = models.ForeignKey('Country', models.DO_NOTHING, blank=True, null=True)
    mobile = models.CharField(max_length=32, blank=True, null=True)
    phone = models.CharField(max_length=32, blank=True, null=True)

    def __str__(self):
        return self.street[:50] + ' ' + self.postal_code + ' ' + self.city[:24]

    class Meta:
        verbose_name_plural = "Addresses"

class BaseProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL,
                                on_delete=models.CASCADE,
                                primary_key=True)
    slug = models.UUIDField(default=uuid.uuid4, blank=True, editable=False)
    # Add more user profile fields here. Make sure they are nullable
    # or with default values
    picture = models.ImageField('Profile picture',
                                upload_to='profile_pics/%Y-%m-%d/',
                                null=True,
                                blank=True)
    bio = models.CharField("Short Bio", max_length=200, blank=True, null=True)
    email_verified = models.BooleanField("Email verified", default=False)
    birthdate = models.DateField(("Birthday"), default=datetime.date.today)

    @property
    def age(self):
        today = datetime.date.today()
        return (today.year - self.birthdate.year) - int(
            (today.month, today.day) <
            (self.birthdate.month, self.birthdate.day))

    class Meta:
        abstract = True

class Country(models.Model):
    name = models.CharField(max_length=64)
    key = models.CharField(max_length=8)

    def __str__(self):
        return self.key + ' - ' + self.name[:50]

    class Meta:
        verbose_name_plural = "Countries"


@python_2_unicode_compatible
class Profile(BaseProfile):
    def __str__(self):
        return "{}'s profile". format(self.user)

class Province(models.Model):
    region = models.ForeignKey('Region', models.DO_NOTHING)
    name = models.CharField(max_length=64)
    key = models.CharField(max_length=8)

    def __str__(self):
        return self.key + ' - ' + self.name[:50]

class Region(models.Model):
    country = models.ForeignKey(Country, models.DO_NOTHING)
    name = models.CharField(max_length=64)
    key = models.CharField(unique=True, max_length=8)

    def __str__(self):
        return self.key + ' - ' + self.name[:50]

src/profiles/forms.py
from __future__ import unicode_literals
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div, Submit, HTML, Button, Row, Field
from crispy_forms.bootstrap import AppendedText, PrependedText, FormActions
from django.contrib.auth import get_user_model
from . import models

User = get_user_model()


class UserForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.layout = Layout(
            Field('name'),
        )

    class Meta:
        model = User
        fields = ['name']


class ProfileForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.layout = Layout(
            Field('picture'),
            Field('birthdate'),
            Field('bio'),
            Submit('update', 'Update', css_class="btn-success"),
        )

    class Meta:
        model = models.Profile
        fields = ['picture', 'birthdate', 'bio']


class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100)
    message = forms.CharField(widget=forms.Textarea)
    sender = forms.EmailField()
    cc_myself = forms.BooleanField(required=False)

src/profiles/views.py
from __future__ import unicode_literals
from django.views import generic
from django.shortcuts import get_object_or_404, redirect
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.core.mail import send_mail
from . import forms
from . import models
from .forms import ContactForm


class ShowProfile(LoginRequiredMixin, generic.TemplateView):
    template_name = "profiles/show_profile.html"
    http_method_names = ['get']

    def get(self, request, *args, **kwargs):
        slug = self.kwargs.get('slug')
        if slug:
            profile = get_object_or_404(models.Profile, slug=slug)
            user = profile.user
        else:
            user = self.request.user

        if user == self.request.user:
            kwargs["editable"] = True
        kwargs["show_user"] = user
        return super().get(request, *args, **kwargs)


class EditProfile(LoginRequiredMixin, generic.TemplateView):
    template_name = "profiles/edit_profile.html"
    http_method_names = ['get', 'post']

    def get(self, request, *args, **kwargs):
        user = self.request.user
        if "user_form" not in kwargs:
            kwargs["user_form"] = forms.UserForm(instance=user)
        if "profile_form" not in kwargs:
            kwargs["profile_form"] = forms.ProfileForm(instance=user.profile)
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        user = self.request.user
        user_form = forms.UserForm(request.POST, instance=user)
        profile_form = forms.ProfileForm(request.POST,
                                         request.FILES,
                                         instance=user.profile)
        if not (user_form.is_valid() and profile_form.is_valid()):
            messages.error(request, "There was a problem with the form. "
                           "Please check the details.")
            user_form = forms.UserForm(instance=user)
            profile_form = forms.ProfileForm(instance=user.profile)
            return super().get(request,
                               user_form=user_form,
                               profile_form=profile_form)
        # Both forms are fine. Time to save!
        user_form.save()
        profile = profile_form.save(commit=False)
        profile.user = user
        profile.save()
        messages.success(request, "Profile details saved!")
        return redirect("profiles:show_self")

src/profiles/templates/profiles/edit_profile.html
{% extends "base.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}
{% load thumbnail %}

{% block title %}{{ block.super }}Profile{% endblock %}

<!-- Benefits of the Django application -->
{% block container %}

<div class="container">
  <h1 class="text-primary">Edit Profile</h1>
  <hr>
  <div class="row">
    <!-- left column -->
    <div class="col-md-3">
      <div class="text-center">
        <img title="profile picture" class="img-circle img-responsive" src="{% thumbnail user.profile.picture|default:'default_profile.png' 140x140 crop %}">
      </div>
    </div>
      
    <!-- edit form column -->
    <div class="col-md-9">
      <h3>Personal info</h3>
      <form enctype="multipart/form-data" method="post">
      {% crispy user_form %}
      {% crispy profile_form %}
      </form>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <a class="btn btn-default pull-right" href="{% url 'accounts:password-change' %}">Change Password</a>
    </div>
  </div>
</div>
{% endblock %}

src/profiles/templates/profiles/show_profile.html
{% extends "base.html" %}

{% load staticfiles %}
{% load thumbnail %}

{% block title %}{{ block.super }}Profile{% endblock %}

{% block navbar-left %} 
{% include "_navbar.html" with active_link="home" %} 
{% endblock %}

{% block container %}

<div class="container profile-head">
  <div class="row">
    <div class="col-sm-10">
      <h1>{{ show_user.get_full_name }}</h1>
      {% if editable %}
      <a href="{% url 'profiles:edit_self' %}" class="btn btn-info">Edit Profile</a>
      {% endif %}
    </div>
    <div class="col-sm-2"><img title="profile picture" class="img-circle img-responsive" src="{% thumbnail show_user.profile.picture|default:'default_profile.png' 140x140 crop %}">
    </div>
  </div>
</div>

<div class="container profile-body">
  <div class="row">
    <div class="col-sm-4">
      <ul class="list-group">
        <li class="list-group-item text-muted">Profile</li>
        <li class="list-group-item text-right"><span class="pull-left"><strong>Email:</strong></span> {{ show_user.email|default:"missing" }}
	  {% if show_user.profile.email_verified %}
	    <span class="glyphicon glyphicon-ok-circle" aria-hidden="true" title="This email address has been verified"></span>
	    <span class="sr-only">Verified</span>
	  {% else %}
	    <span class="glyphicon glyphicon-warning-sign" aria-hidden="true" title="This email address is not verified"></span>
	    <span class="sr-only">Not Verified</span>
	  {% endif %}
	</li>
        <li class="list-group-item text-right"><span class="pull-left"><strong>Joined</strong></span> {{ show_user.date_joined }}</li>
        <li class="list-group-item text-right"><span class="pull-left"><strong>Last seen</strong></span> {{ show_user.last_login }}</li>
      </ul>
    </div>
    <div class="col-sm-8">
      <div class="panel panel-default">
        <div class="panel-heading">{{ show_user.get_full_name }}'s Profile
	  {% if show_user.profile.slug %}
	    <a href="{% url 'profiles:show' show_user.profile.slug %}">
	    	<span class="glyphicon glyphicon-link" aria-hidden="true" title="Profile permalink"></span>
	    	<span class="sr-only">Permalink</span></a> {{ show_user.profile.get_absolute_url }}
	  {% else %}
		<a href="https://github.com/arocks/edge/issues/40" target="_blank"><span>No permalink. See this issue.</span></a>
	  {% endif %}
	</div>
        <div class="panel-body">
	  <strong>Bio</strong>: {{ show_user.profile.bio }}
	</div>
      </div>
    </div>
  </div>
</div>

{% endblock %}