src/accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.LoginView.as_view(), name="login"),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('password-change/', views.PasswordChangeView.as_view(),
         name='password-change'),
    path('password-reset/', views.PasswordResetView.as_view(),
         name='password-reset'),
    path('password-reset-done/', views.PasswordResetDoneView.as_view(),
         name='password-reset-done'),
    path('password-reset/<uuid:uidb64>/<slug:token>/',
         views.PasswordResetConfirmView.as_view(),
         name='password-reset-confirm'),
]

src/ecommerce/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

app_name = 'ecommerce'

urlpatterns = [
    path('', views.ListOrder.as_view()),
    path('<int:pk>/', views.DetailOrder.as_view()),
    url(r'^add-to-cart/(?P<item_id>[-\w]+)/$',
        views.add_to_cart,
        name="add_to_cart"),
    url(r'^cart/$', views.view_cart, name="cart"),
]

src/profiles/urls.py
from django.urls import path
from . import views

app_name = 'profiles'
urlpatterns = [
    path('me/', views.ShowProfile.as_view(), name='show_self'),
    path('me/edit/', views.EditProfile.as_view(), name='edit_self'),
    path('<slug:slug>/', views.ShowProfile.as_view(), name='show'),
]

src/templates/_brandname.html
Amerigoo

src/templates/_navbar.html
{% load i18n %}
<li {% if active_link == "home" %}class="active"{% endif %}><a href="{% url 'home' %}">{% trans 'Home' %}</a></li>
<li {% if active_link == "shop" %}class="active" {% endif %}><a href="{% url 'shop' %}">{% trans 'Shop' %}</a></li>
<li {% if active_link == "about" %}class="active"{% endif %}><a href="{% url 'about' %}">{% trans 'About' %}</a></li>

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
    {% load staticfiles %}
    {% load compress %}
    {% load thumbnail %}
    {% load i18n %}
    
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="{% block description %}{% endblock description %}">
    <meta name="author" content="Arun Ravindran">
    <link rel="shortcut icon" href="{% static 'site/ico/favicon.ico' %}">

    <title>{% block title %}{% include "_brandname.html" %} :: {% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'bootstrap/css/jquery.bootstrap-touchspin.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this site -->
    {% block styles %}
    <link href="{% static 'site/css/main.css' %}" rel="stylesheet">
    <link href="{% static 'site/js/vendor/essential-grid/public/assets/css/settings.css' %}" rel="stylesheet">
    <link href="{% static 'site/js/vendor/essential-grid/public/assets/css/lightbox.css' %}" rel="stylesheet">
    <link href="{% static 'site/js/vendor/revslider/public/assets/css/settings.css' %}" rel="stylesheet">
    <link href="{% static 'site/js/vendor/woocommerce/assets/css/woocommerce-layout.css' %}" rel="stylesheet">
    <link href="{% static 'site/js/vendor/woocommerce/assets/css/woocommerce.css' %}" rel="stylesheet">
    <link href="{% static 'site/js/vendor/woocommerce/assets/css/prettyPhoto.css' %}" rel="stylesheet">
    <link href="{% static 'site/js/vendor/swiper/swiper.css' %}" rel="stylesheet">
    <link href="{% static 'site/css/fontello/css/fontello.css' %}" rel="stylesheet">
    <link href="{% static 'site/css/style.css' %}" rel="stylesheet">
    <link href="{% static 'site/css/core.animation.css' %}" rel="stylesheet">
    <link href="{% static 'site/css/shortcodes.css' %}" rel="stylesheet">
    <link href="{% static 'site/css/woo-style.css' %}" rel="stylesheet">
    <link href="{% static 'site/css/skin.css' %}" rel="stylesheet">
    <link href="{% static 'site/css/responsive.css' %}" rel="stylesheet">
    <link href="{% static 'site/css/skin.responsive.css' %}" rel="stylesheet">
    <link href="https://use.fontawesome.com/releases/v5.2.0/css/brands.css" rel="stylesheet" integrity="sha384-nT8r1Kzllf71iZl81CdFzObMsaLOhqBU1JD2+XoAALbdtWaXDOlWOZTR4v1ktjPE" crossorigin="anonymous">
    <link href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" rel="stylesheet" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
    {% endblock styles %}
    {% compress css %}
    <link href="{% static 'site/css/custom.less' %}" media="all" rel="stylesheet" type="text/less" /> 
    <link href="{% static 'site/css/custom-responsive.less' %}" media="all" rel="stylesheet" type="text/less" />
    {% endcompress %}

    <!-- Custom tags for the head tag -->
    {% block extrahead %}
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/jquery.bootstrap-touchspin.min.js' %}"></script>
    {% endblock extrahead %}

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    {% block navbar %}
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'home' %}">
            {% block navbar-brand %}
              <img src="{% static 'site/img/logo.png' %}" alt="logo">
              {% include "_brandname.html" %}
            {% endblock %}
          </a>
        </div>
        {% block navbar-menu %}
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            {% block navbar-left %}{% endblock %}
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <a href="{% url 'ecommerce:cart' %}">
              <span class="sc_icon btn-cart icon-shopping-cart13 alignleft"></span>
            </a>
            {% block navbar-right %}
              {% if user.is_authenticated %}
                {% if user.is_staff %}
                <li><a href="{% url 'admin:index' %}">Admin</a></li>
                {% endif %}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle profile-menu" data-toggle="dropdown">
                  <img src="{% thumbnail user.profile.picture|default:'default_profile.png' 30x30 crop %}" alt="" />
                  {{ user.get_full_name|truncatechars:20 }}
                  <span class="caret"></span>
                    </a>
		    
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="{% url 'profiles:show_self' %}">Profile</a></li>
                    <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                  </ul>
                </li>
              {% endif %}
            {% endblock %}
          </ul>
          </ul>
        </div><!--/.nav-collapse -->
        {% endblock %}
    </div>
    {% endblock navbar %}

    {% block messages %}
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-{{ message.tags }}">  <!-- singular -->
            <a class="close" data-dismiss="alert">×</a>
            {{ message|safe }}
          </div>
        {% endfor %}
      {% endif %}
    {% endblock %}

    {% block splash %}
    {% endblock splash %}
    
    {% block container %}
    <div class="container">

      <div class="starter-template">
        <h1>New Project</h1>
        <p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a mostly barebones HTML document.</p>
      </div>

    </div><!-- /.container -->
    {% endblock container %}

    <!-- Site footer -->
    {% block footer %}
    <footer class="footer_wrap widget_area scheme_original mt_80">
        <div class="container">
          <div class="row">
    
            <aside class="col-md-3">
              <div class="logo">
                  <a class="navbar-brand pd-0 mb-30" href="{% url 'shop' %}">
                    <img src="/static/site/img/logo.png" alt="logo"> Amerigoo
                  </a>
                </a>
              </div>
              <div class="language">
                <form action="{% url 'set_language' %}" method="post">{% csrf_token %}
                  <input name="next" type="hidden" value="{{ redirect_to }}">
                  <select name="language">
                    {% get_current_language as LANGUAGE_CODE %} 
                    {% get_available_languages as LANGUAGES %} {% get_language_info_list for LANGUAGES as languages %} 
                    {% for language in languages %}
                    <option value="{{ language.code }}" {% if language.code == LANGUAGE_CODE %} selected{% endif %}>
                      {{ language.name_local }} ({{ language.code }})
                    </option>
                    {% endfor %}
                  </select>
                  <input type="submit" value="Go" />
                </form>
              </div>
            </aside>
    
            <aside class="col-md-3 widget widget_recent_posts">
              <h5 class="widget_title">Informacion</h5>
              <article class="post_item with_thumb first">
                <div class="post_content">
                  <h6 class="post_title">
                    <a href="{% url 'about' %}">Sobre nosotros</a>
                  </h6>
                </div>
              </article>
              <article class="post_item with_thumb">
                <div class="post_content">
                  <h6 class="post_title">
                    <a href="{% url 'contact' %}">Contacto</a>
                  </h6>
                </div>
              </article>
            </aside>
    
            <aside class="col-md-3 widget widget_socials">
              <h5 class="widget_title">Siguenos</h5>
    
              <div class="widget_inner">
                <div class="logo_descr">Mantente informado a través de nuestros canales de redes sociales para formar parte de
                  la mejor experiencia gastronómica.
                </div>
                <div class="sc_socials sc_socials_type_icons sc_socials_shape_round sc_socials_size_tiny">
                  <div class="sc_socials_item">
                    <a href="#"><i class="fab fa-facebook fa-2x"></i> Facebook</a>
                  </div>
                  <div class="sc_socials_item">
                    <a href="#"><i class="fab fa-twitter fa-2x"></i> Twitter</a>
                  </div>
                  <div class="sc_socials_item">
                    <a href="#"><i class="fab fa-instagram fa-2x"></i> Instagram</a>
                  </div>
                </div>
              </div>
            </aside>
    
            <aside class="col-md-3 widget widget_socials">
              <h5 class="widget_title">Comunidad</h5>
    
              <div class="logo_descr">Forma parte de nuestra comunidad en telegram, donde podrás tener contacto directo con amantes
                de la gastronomía como tú.
              </div>
              <div class="sc_socials sc_socials_type_icons sc_socials_shape_round sc_socials_size_tiny">
                <div class="sc_socials_item">
                  <a href="#"><i class="fab fa-telegram fa-2x"></i>Telegram</a>
                </div>
              </div>
            </aside>
    
          </div>
        </div>
    </footer>
  
      <!-- Some social button for contact will do -->
      <a name="contact"></a>
      <div class="container">
            <div class="footer">
        <div class="row">
          <div class="col-lg-6">
              <p>&copy; Amerigoo {% now 'Y' %}</p>
          </div>
          <div class="col-lg-6 text-right">
             &copy; Todos los derechos reservados.
          </div>
        </div>
            </div>
      </div>
    {% endblock %}

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block scripts %}
    <script src="{% static 'site/js/site.js' %}"></script>
    <script src="{% static 'site/js/vendor/_packed.js' %}"></script>
    <script src="{% static 'site/js/vendor/essential-grid/public/assets/js/lightbox.js' %}"></script>
    <script src="{% static 'site/js/vendor/essential-grid/public/assets/js/jquery.themepunch.tools.min.js' %}"></script>
    <script src="{% static 'site/js/vendor/essential-grid/public/assets/js/jquery.themepunch.essential.min.js' %}"></script>
    <script src="{% static 'site/js/vendor/revslider/public/assets/js/jquery.themepunch.revolution.min.js' %}"></script>
    <script src="{% static 'site/js/vendor/revslider/public/assets/js/extensions/revolution.extension.parallax.min.js' %}"></script>
    <script src="{% static 'site/js/vendor/revslider/public/assets/js/extensions/revolution.extension.slideanims.min.js' %}"></script>
    <script src="{% static 'site/js/vendor/revslider/public/assets/js/extensions/revolution.extension.video.min.js' %}"></script>
    <script src="{% static 'site/js/vendor/revslider/public/assets/js/extensions/revolution.extension.navigation.min.js' %}"></script>
    <script src="{% static 'site/js/vendor/revslider/public/assets/js/extensions/revolution.extension.layeranimation.min.js' %}"></script>
    <script src="{% static 'site/js/custom/_main.js' %}"></script>
    <script src="{% static 'site/js/custom/core.utils.js' %}"></script>
    <script src="{% static 'site/js/custom/core.init.js' %}"></script>
    <script src="{% static 'site/js/custom/shortcodes.js' %}"></script>
    <script src="{% static 'site/js/vendor/photostack/modernizr.min.js' %}"></script>
    <script src="{% static 'site/js/vendor/superfish.min.js' %}"></script>
    <script src="{% static 'site/js/vendor/jquery.slidemenu.js' %}"></script>
    <script src="{% static 'site/js/vendor/woocommerce/assets/js/jquery.prettyPhoto.min.js' %}"></script>
    <script src="{% static 'site/js/vendor/woocommerce/assets/js/jquery.prettyPhoto.init.min.js' %}"></script>
    <script src="{% static 'site/js/vendor/swiper/swiper.js' %}"></script>
    <script src="{% static 'site/js/vendor/widget.min.js' %}"></script>
    <script src="{% static 'site/js/vendor/core.min.js' %}"></script>
    <script src="{% static 'site/js/vendor/tabs.min.js' %}"></script> 
    {% endblock scripts %}
  </body>
</html>

src/templates/cart.html
{% extends "base.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }}About{% endblock %} 

{% block navbar-left %} 
    {% include "_navbar.html" with active_link="about" %} 
{% endblock %}

{% block container %}
<body class="page body_filled article_style_stretch top_panel_above sidebar_hide">
    <div class="page_content_wrap">
        <div class="container">
            <h2><a href="{% url 'profiles:show_self' %}">Mi cuenta</a><small> \ Cesta</small></h2>
            <div class="row">
                <div class="col-md-9">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title">Mi cesta</h3>
                    </div>
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th scope="col"><b>Producto</b></th>
                                <th scope="col"><b>Precio</b></th>
                                <th scope="col" style="width:60px;"><b>Unidades</b></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for orderline in order %}
                            <tr>
                                <td>{{ orderline.product.name }}</td>
                                <td>{{ orderline.product.unit_price | floatformat:2 }}&euro;</td>
                                <td><input id="demo1" type="text" value="{{ orderline.amount }}" name="demo1">
                                <script>
                                    $("input[name='demo1']").TouchSpin();
                                </script></td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    </div>
                </div>
                <div class="col-md-3">
                     {% include "_resume.html" %}
                </div>
            </div>
        </div>
    </div>
</body>
{% endblock container %}

src/templates/home.html
{% extends "base.html" %} 

{% load staticfiles %} 
{% load crispy_forms_tags %}

{% block title %}
{{ block.super }} Home {% endblock%} 

{% block navbar-left %} 
{% include "_navbar.html" with active_link="home" %}
{% endblock %} 

{% block navbar-right %} 

{% if not user.is_authenticated %}
<a class="btn btn-default" href="{% url 'accounts:login' %}" role="button">Log in</a>
<a class="btn btn-primary" href="{% url 'accounts:signup' %}" role="button">Sign up</a>
{% else %} 
{{ block.super }} 
{% endif %} 
{% endblock %} 
{% block splash %}
<div class="page body_filled article_style_stretch top_panel_over sidebar_hide main_page">
    <div class="body_wrap">
        <div class="page_wrap">
            <div class="top_panel_fixed_wrap"></div>

            <!--<?= $this->render('@partials/menu.php') ?>
            <?= $this->render('@partials/menu_mobile.php') ?> -->

            <div class="page_content_wrap page_paddings_no">
                <div class="content_wrap">
                    <div class="content">
                        <article class="post_item post_item_single page">
                            <div class="post_content">
                            <!-- <?= $this->render('@partials/slider.php') ?> -->
                             {% include "_slider.html" %}
                        </div>
                    </article>
                </div>
            </div>
        </div>

    </div>

</div>
</div>
{% endblock splash %} 

{% block container %}
<!-- Benefits of the Django application -->
<a name="about"></a>
{% endblock container %} 

{% block footer %}
{% endblock %}

src/templates/shop.html
{% extends "base.html" %} 

{% load staticfiles %} 
{% load crispy_forms_tags %}
{% load sitetree %}
{% load i18n %}

{% block title %}
{{ block.super }} Home {%endblock%} 

{% block navbar-left %} {% include "_navbar.html" with active_link="home" %} {% endblock %} 

{% block navbar-right%} 
{% if not user.is_authenticated %}
<a class="btn btn-default" href="{% url 'accounts:login' %}" role="button">Log in</a>
<a class="btn btn-primary" href="{% url 'accounts:signup' %}" role="button">Sign up</a>
{% else %} 
{{ block.super }} 
{% endif %} 
{% endblock %} 
{% block splash %}

<body class="page body_filled article_style_stretch top_panel_above sidebar_hide">

    <div class="body_wrap">
        <div class="page_wrap">
            <div class="top_panel_fixed_wrap"></div>

            <header class="top_panel_wrap top_panel_style_4 scheme_original">
                <div class="top_panel_wrap_inner top_panel_inner_style_4 top_panel_position_above">
                    <!-- {% include "_menu.html" %}
                    <!-- <?= $this->render('@partials/topbar.php') ?>
                    <?= $this->render('@partials/menu_shop.php') ?>
                    <?= $this->render('@partials/menu_mobile.php') ?> -->
                </div>
            </header>

            <div class="page_content_wrap page_paddings_no">
                <div class="content_wrap">
                    <div class="content">
                        <article class="post_item post_item_single page">
                            <div class="post_content">

                                {% include "_slider.html" %}
                                {% include "_carrousel.html" with title="Best Selling Products" products=products_best_selling grid="esg-grid-19-1" nav="esg-fgc-19" %}

                                <section>
                                    <div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <div class="sc_section banner_big_bg_3 banner_big_block h252" data-animation="animated fadeIn normal">
                                                    <div class="sc_section_inner">
                                                        <div class="sc_section_overlay">
                                                            <div class="sc_section_content">
                                                                <div class="columns_wrap sc_columns columns_nofluid no_margins sc_columns_count_2">
                                                                    <div class="column-1_2 sc_column_item sc_column_item_1 odd first">
                                                                    </div>
                                                                    <div class="column-1_2 sc_column_item sc_column_item_2 right even">
                                                                        <h3 class="sc_title">GIFT certificates</h3>
                                                                        <p>Give the perfect gift every time &#8211; Organic
                                                                            Store gift certificates!</p>
                                                                        <a href="#" class="sc_button sc_button_round sc_button_style_filled sc_button_scheme_original sc_button_size_medium">CLICK
                                                                            TO ORDER</a>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <div class="sc_section banner_big_bg_4 banner_big_block h252" data-animation="animated fadeIn normal">
                                                    <div class="sc_section_inner">
                                                        <div class="sc_section_overlay">
                                                            <div class="sc_section_content">
                                                                <div class="columns_wrap sc_columns columns_nofluid no_margins sc_columns_count_2">
                                                                    <div class="column-1_2 sc_column_item sc_column_item_1 odd first">
                                                                    </div>
                                                                    <div class="column-1_2 sc_column_item sc_column_item_2 right even">
                                                                        <h3 class="sc_title">GIFT certificates</h3>
                                                                        <p>Give the perfect gift every time &#8211; Organic
                                                                            Store gift certificates!</p>
                                                                        <a href="#" class="sc_button sc_button_round sc_button_style_filled sc_button_scheme_original sc_button_size_medium">CLICK
                                                                            TO ORDER</a>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </section>

                                {% include "_carrousel.html" with title="Featured Products" products=products_best_selling grid="esg-grid-18-1" nav="esg-fgc-18" %}

                                <section>
                                    <div>
                                        <div class="sc_section imgc section_img_1">
                                            <div class="sc_section_inner">
                                                <div class="sc_section_overlay">
                                                    <div class="sc_section_content">
                                                        <div class="columns_wrap sc_columns columns_nofluid sc_columns_count_2">
                                                            <div class="column-1_2 sc_column_item sc_column_item_1 odd first">
                                                            </div>
                                                            <div class="column-1_2 sc_column_item sc_column_item_2 even">
                                                                <h3 class="sc_title sc_title_style_2 sc_align_center">WHEN
                                                                    QUALITY MATTERS TO YOU<br /> AND YOUR CUSTOMERS</h3>
                                                            </div>
                                                        </div>
                                                        <div class="es_230"></div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </section>

                                <section class="spt_40 spb_75 mt_30 mb_20">
                                    <div>
                                        <div class="columns_wrap">
                                            {% include "_column.html" with title="New Products" %}
                                            {% include "_column.html" with title="Top Sellers" %}
                                            {% include "_column.html" with title="Sale Products" %}
                                            {% include "_column.html" with title="Top Rate" %}
                                        </div>
                                    </div>
                                </section>

                                <section class="spb_25">
                                    <div class="content_padder">
                                        <div class="columns_wrap">
                                            <div class="col-md-4">
                                                <div class="sc_section banner_small_bg_1 banner_block" data-animation="animated fadeInUp normal">
                                                    <div class="sc_section_inner">
                                                        <div class="sc_section_overlay">
                                                            <div class="sc_section_content">
                                                                <span class="sc_icon icon-smiley3 alignleft"></span>
                                                                <h4 class="sc_title sc_title_regular">Sale! Up to 50% off</h4>
                                                                <p>For all products only NOW</p>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-md-4">
                                                <div class="sc_section banner_small_bg_2 banner_block" data-animation="animated fadeInUp normal">
                                                    <div class="sc_section_inner">
                                                        <div class="sc_section_overlay">
                                                            <div class="sc_section_content">
                                                                <span class="sc_icon icon-airplane116 alignleft"></span>
                                                                <h4 class="sc_title sc_title_regular">FREE SHIPPING</h4>
                                                                <p>For all orders over $100</p>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-md-4">
                                                <div class="sc_section banner_small_bg_3 banner_block" data-animation="animated fadeInUp normal">
                                                    <div class="sc_section_inner">
                                                        <div class="sc_section_overlay">
                                                            <div class="sc_section_content">
                                                                <span class="sc_icon icon-like83 alignleft"></span>
                                                                <h4 class="sc_title sc_title_regular">Money back</h4>
                                                                <p>If the item didn&#8217;t suit you</p>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </section>

                            </div>
                        </article>
                    </div>
                </div>
            </div>

        </div>

    </div>

    <a href="#" class="scroll_to_top icon-up" title="Scroll to top"></a>

    {% endblock splash %} {% block container %}
    <a name="about"></a>
    {% endblock container %}